//! Every `cosmonic:notify` host call the playground makes, in one file.
//!
//! This is the part worth reading. The host exports `cosmonic:notify/notifier`
//! and `cosmonic:notify/events`; `wit_bindgen::generate!` turns the WIT in
//! `wit/` into the `bindings` module below, and from there it is ordinary
//! function calls. There is nothing to install and nothing to configure — the
//! interface is available to any component whose Workload declares it in
//! `spec.hostInterfaces`.

use serde::Deserialize;

mod bindings {
    wit_bindgen::generate!({
        world: "playground",
        path: "wit",
        // We only import; the HTTP export is generated by the
        // `wasmcloud-component` macro in lib.rs.
        generate_all,
    });
}

use bindings::cosmonic::notify::events;
use bindings::cosmonic::notify::notifier;
use bindings::cosmonic::notify::types as t;

/// What the playground page POSTs. Every field maps 1:1 onto the WIT record so
/// the page can be read as documentation for the interface.
#[derive(Deserialize)]
#[serde(default)]
struct Request {
    title: String,
    body: String,
    /// "low" | "normal" | "critical"
    urgency: String,
    actions: Vec<Action>,
    input: Option<Input>,
    /// Target for a click on the notification body itself.
    default_target: Option<Target>,
    tag: Option<String>,
    timeout_ms: Option<u32>,
}

impl Default for Request {
    fn default() -> Self {
        Self {
            title: String::new(),
            body: String::new(),
            urgency: "normal".into(),
            actions: Vec::new(),
            input: None,
            default_target: None,
            tag: None,
            timeout_ms: None,
        }
    }
}

#[derive(Deserialize)]
struct Action {
    id: String,
    label: String,
    #[serde(flatten)]
    target: Target,
}

#[derive(Deserialize)]
struct Input {
    id: String,
    label: String,
    placeholder: Option<String>,
}

/// `{"target":"callback"}` | `{"target":"url","value":"https://…"}` |
/// `{"target":"deep-link","value":"workloads/default/x"}`
#[derive(Deserialize)]
struct Target {
    target: String,
    #[serde(default)]
    value: String,
}

impl Target {
    fn to_wit(&self) -> t::ActionTarget {
        match self.target.as_str() {
            "url" => t::ActionTarget::Url(self.value.clone()),
            "deep-link" => t::ActionTarget::DeepLink(self.value.clone()),
            _ => t::ActionTarget::Callback,
        }
    }
}

impl Request {
    fn to_wit(&self) -> t::Notification {
        t::Notification {
            title: self.title.clone(),
            body: self.body.clone(),
            urgency: match self.urgency.as_str() {
                "low" => t::Urgency::Low,
                "critical" => t::Urgency::Critical,
                _ => t::Urgency::Normal,
            },
            actions: self
                .actions
                .iter()
                .map(|a| t::Action {
                    id: a.id.clone(),
                    label: a.label.clone(),
                    target: a.target.to_wit(),
                })
                .collect(),
            input: self.input.as_ref().map(|i| t::TextInput {
                id: i.id.clone(),
                label: i.label.clone(),
                placeholder: i.placeholder.clone(),
            }),
            default_target: self.default_target.as_ref().map(|t| t.to_wit()),
            tag: self.tag.clone(),
            timeout_ms: self.timeout_ms,
        }
    }
}

// ---- The host calls ------------------------------------------------------

/// `notifier.capabilities()` — what this machine can actually render. Worth
/// calling before you build a notification: on GNOME `inline-reply` is false
/// and the host will degrade your text input to a button.
pub fn capabilities_json() -> String {
    let c = notifier::capabilities();
    format!(
        r#"{{"available":{},"backend":{},"actions":{},"inlineReply":{},"urgency":{},"persistent":{},"maxActions":{}}}"#,
        c.available,
        json_str(&c.backend),
        c.actions,
        c.inline_reply,
        c.urgency,
        c.persistent,
        c.max_actions
    )
}

/// `notifier.post()` — fire and forget. The answer arrives later via `pull`.
pub fn post_json(raw: &str) -> (u16, String) {
    let req = match parse(raw) {
        Ok(r) => r,
        Err(e) => return (400, crate::error_json(&e)),
    };
    match notifier::post(&req.to_wit()) {
        Ok(id) => (200, format!(r#"{{"id":{id}}}"#)),
        Err(e) => (200, format!(r#"{{"error":{}}}"#, json_str(&describe(&e)))),
    }
}

/// `notifier.request()` — fire and WAIT. This call does not return until the
/// user answers, the notification expires, or the host's ceiling is hit, so
/// the HTTP request in front of it blocks for exactly as long as the human
/// takes. That is the whole point of the call.
pub fn request_json(raw: &str) -> (u16, String) {
    let req = match parse(raw) {
        Ok(r) => r,
        Err(e) => return (400, crate::error_json(&e)),
    };
    match notifier::request(&req.to_wit()) {
        Ok(response) => (
            200,
            format!(r#"{{"response":{}}}"#, response_json(&response)),
        ),
        Err(e) => (200, format!(r#"{{"error":{}}}"#, json_str(&describe(&e)))),
    }
}

/// `notifier.close()` — withdraw a notification. Its pending response resolves
/// as `expired`. Closing an id you do not own is a silent no-op.
pub fn close_json(raw: &str) -> (u16, String) {
    #[derive(Deserialize)]
    struct Close {
        id: u64,
    }
    let close: Close = match serde_json::from_str(raw) {
        Ok(c) => c,
        Err(e) => {
            return (
                400,
                crate::error_json(&format!("expected {{\"id\":<number>}}: {e}")),
            )
        }
    };
    match notifier::close(close.id) {
        Ok(()) => (200, r#"{"closed":true}"#.to_string()),
        Err(e) => (200, format!(r#"{{"error":{}}}"#, json_str(&describe(&e)))),
    }
}

/// `events.pull()` — drain the responses queued for THIS COMPONENT.
///
/// The queue is per component, not per instance, which is what makes `post`
/// usable at all from a request-scoped component like this one: the invocation
/// that posted is long gone by the time the user clicks, and this invocation
/// picks the answer up. `0` means "poll, do not block".
pub fn events_json() -> String {
    match events::pull(0) {
        Ok(list) => {
            let list: Vec<events::Event> = list;
            let items: Vec<String> = list
                .iter()
                .map(|e| {
                    format!(
                        r#"{{"id":{},"response":{}}}"#,
                        e.id,
                        response_json(&e.response)
                    )
                })
                .collect();
            format!(r#"{{"events":[{}]}}"#, items.join(","))
        }
        Err(e) => format!(r#"{{"error":{}}}"#, json_str(&describe(&e))),
    }
}

// ---- Plumbing ------------------------------------------------------------

fn parse(raw: &str) -> Result<Request, String> {
    let req: Request = serde_json::from_str(raw).map_err(|e| format!("invalid request: {e}"))?;
    if req.title.trim().is_empty() {
        // The host rejects this too — catching it here just gives a better
        // message than `invalid("title is empty")` coming back off the wire.
        return Err("a notification needs a title".into());
    }
    Ok(req)
}

fn response_json(r: &t::Response) -> String {
    match r {
        t::Response::Activated => r#"{"kind":"activated"}"#.to_string(),
        t::Response::Action(id) => format!(r#"{{"kind":"action","id":{}}}"#, json_str(id)),
        t::Response::Reply((id, text)) => format!(
            r#"{{"kind":"reply","id":{},"text":{}}}"#,
            json_str(id),
            json_str(text)
        ),
        t::Response::Dismissed => r#"{"kind":"dismissed"}"#.to_string(),
        t::Response::Expired => r#"{"kind":"expired"}"#.to_string(),
    }
}

/// Turn a `notify-error` into something a human can act on. Each variant means
/// a genuinely different thing, and a playground should say which.
fn describe(e: &t::NotifyError) -> String {
    match e {
        t::NotifyError::Denied => {
            "denied — notifications are revoked for this component in Settings → Notifications"
                .into()
        }
        t::NotifyError::Throttled => "throttled — too many notifications too quickly".into(),
        t::NotifyError::Unavailable => {
            "unavailable — this machine cannot show notifications right now. Check \
             /capabilities for the reason (headless session, macOS authorization, or a \
             daemon with no bundle identity)."
                .into()
        }
        t::NotifyError::Invalid(m) => format!("invalid — {m}"),
        t::NotifyError::Platform(m) => format!("platform error — {m}"),
    }
}

fn json_str(s: &str) -> String {
    serde_json::to_string(s).unwrap_or_else(|_| "\"\"".into())
}
